### ISSUE TITLE
cannot compile with nightly 1.59

### ISSUE THREAD

**Issue by seanjensengrey** [sisshiki1969/monoasm#1]
This looks like a really neat project, I'd love to play around with it. What was the last version of nightly that you used to compile? 

The version I use below no longer supports the experimental features.

```
 % rustc +nightly --version
rustc 1.59.0-nightly (e95e084a1 2021-12-19)
```

First two errors from `cargo +nightly build`

are

```
% cargo +nightly build 2>&1 | more
   Compiling monoasm v0.1.0 (/Users/seanj/tt/source-archives/github.com/sisshiki1969/monoasm/monoasm)
error[E0557]: feature has been removed
 --> monoasm/src/lib.rs:2:12
  |
2 | #![feature(const_raw_ptr_to_usize_cast)]
  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^ feature has been removed
  |
  = note: at compile-time, pointers do not have an integer value, so these casts cannot be properly supported

error: cannot find macro `asm` in this scope
  --> monoasm/src/test.rs:26:17
   |
26 |                 asm!(
   |                 ^^^
...
48 |     reg_save!(rax);
   |     -------------- in this macro invocation
   |
   = note: consider importing one of these items:
           std::arch::asm
           core::arch::asm
   = note: this error originates in the macro `reg_save` (in Nightly builds, run with -Z macro-backtrace for more info)
```

**Comment by sisshiki1969** [comment]
So sorry for the late reply.
I confirmed that 1.62.0-nightly can compile this repo.
Do you still have a problem?
